from typing import Dict

product_list: list[Dict] = [
    {
        "id": 0,
        "Name": "TerraStore Large Green Tent",
        "Price": 369.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/7dLCRxDv/image-9.webp",
    },
    {
        "id": 1,
        "Name": "PineCoal Fire-Starting Kit",
        "Price": 49.99,
        "Quantity": 20,
        "Category": "Fire Starters",
        "Img": "https://i.ibb.co/jvnd2Ptv/image-2.webp",
    },
    {
        "id": 2,
        "Name": "FirePeak Large Headlight Orange ",
        "Price": 39.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://cdn.myimgs.org/images/43305/image_3.png",
    },
    {
        "id": 3,
        "Name": "Frosty Small Sleeping Mat ",
        "Price": 199.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/bgmXn67N/image-4.webp",
    },
    {
        "id": 4,
        "Name": "Mountain 20L Blue Backpack",
        "Price": 179.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/VpwddzLv/image-5.webp",
    },
    {
        "id": 5,
        "Name": "TerraStore 15L Container",
        "Price": 49.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Fb1HVG7j/image-6.webp",
    },
    {
        "id": 6,
        "Name": "IronTrail Camping Utensils Set",
        "Price": 39.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/994w97Kq/image-8.webp",
    },
    {
        "id": 7,
        "Name": "TerraStore Medium Orange Tent",
        "Price": 279.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/9mN3PSnp/image-1.webp",
    },
    {
        "id": 8,
        "Name": "PineCoal Single Portable Stove",
        "Price": 59.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/mFzMDR4G/image-10.webp",
    },
    {
        "id": 9,
        "Name": "Frosty 1.5L Stainless Steel Thermos",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Q7HWtZX2/image-11.webp",
    },
    {
        "id": 10,
        "Name": "Snow Peak Titanium Mug",
        "Price": 49.59,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/RpXYD8zm/image-42.webp",
    },
    {
        "id": 11,
        "Name": "HUNTER Multi-tool HIKE ",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/jZhchyMY/image-12.webp",
    },
    {
        "id": 12,
        "Name": "TerraStore Camping Lamp H400",
        "Price": 54.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/YBd53w8w/image-13.webp",
    },
    {
        "id": 13,
        "Name": "APEX Solar PowerBank SS50",
        "Price": 129.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/sdbqgcKh/image-14.webp",
    },
    {
        "id": 14,
        "Name": "Wild Trail Camping Utensils Orange",
        "Price": 64.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/gMj7KTCp/image-15.webp",
    },
    {
        "id": 15,
        "Name": "APEX WoodPath Trekking Poles",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/7tWQZffc/image-16.webp",
    },
    {
        "id": 16,
        "Name": "TerraStore R-Series Camping Chair",
        "Price": 219.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/pr1VMqx6/image-17.webp",
    },
    {
        "id": 17,
        "Name": "APEX Isobutane-Propane Mix",
        "Price": 66.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Kzp16dSD/image-18.webp",
    },
    {
        "id": 18,
        "Name": "NatureHike Camping Cup",
        "Price": 44.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Fb8GqyGX/image-19.webp",
    },
    {
        "id": 19,
        "Name": "NatureHike 15L Blue Backpack",
        "Price": 129.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/jZsB6Vgm/image-20.webp",
    },
    {
        "id": 20,
        "Name": "PELICAN Portable Hardcase",
        "Price": 1699.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/pv18srFp/image-38.webp",
    },
    {
        "id": 21,
        "Name": " AEROSHIELD X8 Expedition Drone",
        "Price": 6399.99,
        "Quantity": 20,
        "Category": "Drone",
        "Img": "https://i.ibb.co/PzGqL2m5/image-22.webp",
    },
    {
        "id": 22,
        "Name": "HUNTER 10x50 42mm Binoculars",
        "Price": 359.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Tx8hTPQ9/image-23.webp",
    },
    {
        "id": 23,
        "Name": "APEX Tracker PRO4 Lite",
        "Price": 2449.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/fzWkQjL5/image-24.webp",
    },
    {
        "id": 24,
        "Name": "HUNTER Emergency Kit Pro",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "Emergency Kit",
        "Img": "https://i.ibb.co/Rrvwk7V/image-25.webp",
    },
    {
        "id": 25,
        "Name": "BAOFENG Dual UWR-X5",
        "Price": 4799.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/zh9MWSCy/image-26.webp",
    },
    {
        "id": 26,
        "Name": "APEX Counter Assault Bear Spray",
        "Price": 39.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/FbTPW0f0/image-27.webp",
    },
    {
        "id": 27,
        "Name": "APEX Tactical Emergency Kit",
        "Price": 149.99,
        "Quantity": 20,
        "Category": "Emergency Kit",
        "Img": "https://i.ibb.co/BXW4kBv/image-28.webp",
    },
    {
        "id": 28,
        "Name": "IronTrail 32cm Camping Knife ",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/GQ6TNc2f/image-29.webp",
    },
    {
        "id": 29,
        "Name": "HUNTER Water Filtration Pod",
        "Price": 479.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/JRbDNMYP/image-30.webp",
    },
    {
        "id": 30,
        "Name": "BOAFENG XER-N2",
        "Price": 1899.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Fq3v7tp2/image-31.webp",
    },
    {
        "id": 31,
        "Name": "APEX Solar PowerBank SS90",
        "Price": 379.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Lzw3s5Tm/image-32.webp",
    },
    {
        "id": 32,
        "Name": "JETBOIL Jet Power Stove",
        "Price": 179.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/3JJr4Vw/image-33.webp",
    },
    {
        "id": 33,
        "Name": "IronTrail Portable Solar Panel System",
        "Price": 1299.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/PZ4Z8p3j/image-34.webp",
    },
    {
        "id": 34,
        "Name": "HUNTER AQUA Water Filtration ",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/DgfmWVSC/image-35.webp",
    },
    {
        "id": 35,
        "Name": "APEX RR-7 Camping Cot",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/rRjz0SxK/image-36.webp",
    },
    {
        "id": 36,
        "Name": "Frosty Electric Cooler PR5",
        "Price": 1549.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/qYLJmcRg/image-37.webp",
    },
    {
        "id": 37,
        "Name": "AEROSHIELD X5 Expedition Drone",
        "Price": 4379.99,
        "Quantity": 20,
        "Category": "Drone",
        "Img": "https://i.ibb.co/N2MgdM64/image-21.png",
    },
    {
        "id": 38,
        "Name": "HUNTER TIGER-2 Camping Watch",
        "Price": 799.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/pv3JsHKB/image-39.webp",
    },
    {
        "id": 39,
        "Name": "APEX Headlamp Lunar F300",
        "Price": 79.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/Tqq9s4Bk/image-40.webp",
    },
    {
        "id": 40,
        "Name": "Solo Stove Smokeless Fire Pit",
        "Price": 119.99,
        "Quantity": 20,
        "Category": "None",
        "Img": "https://i.ibb.co/bM0K0qRG/image-41.webp",
    },
]
